version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"  # Expose port 9001 for the Go application
    environment:
      - ENV_VAR=value  # Replace with your actual environment variables
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
